#start/sys_update.bash
#start/pre_requisites.bash
#start/python.bash
#start/python_lib.bash
#start/common_libraries.bash
#start/perl_lib.bash
#start/chipster_main.bash
#start/macs_pre.bash
#start/macs2_pre.bash
#start/htseq_pre.bash
