#external_tools/BEDTools.bash
#external_tools/BLAST.bash
#external_tools/Bowtie_2.bash
#external_tools/Bowtie.bash
#external_tools/BWA.bash
#external_tools/ClusterBuster.bash
#external_tools/ConsensuPathDB.bash
#external_tools/Cufflinks_1.bash
#external_tools/Cufflinks_2.bash
#external_tools/DEXSeq.bash
#external_tools/dimont.bash
#external_tools/EMBOSS.bash
#external_tools/Express.bash
#external_tools/FastQC.bash
#external_tools/Fastx_links.bash
#external_tools/fseq.bash
#external_tools/GATK.bash
#external_tools/Genome_annotations.bash
#external_tools/Genome_bundles.bash
#external_tools/HTSeq.bash
#external_tools/Jaspar.bash
#external_tools/MACS.bash
#external_tools/Mafft.bash
#external_tools/meme.bash
#external_tools/miRNA_mapping_data.bash
#external_tools/mothur.bash
#external_tools/phylipnew.bash
#external_tools/Picard_tools.bash
#external_tools/primer3.bash
#external_tools/prinseq.bash
#external_tools/QDNAseq.bash
#external_tools/RSeQC.bash
#external_tools/SAM_tools.bash
#external_tools/tabix.bash
#external_tools/tagcleaner.bash
#external_tools/Tophat_2.bash
#external_tools/Tophat.bash
#external_tools/Trimmomatic.bash
#external_tools/vcftools.bash
#external_tools/vienna.bash
#external_tools/Weeder.bash
