package fi.csc.chipster.web.model;

import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;

import fi.csc.chipster.web.tooledit.ToolEditor;
import fi.csc.microarray.description.SADLDescription;
import fi.csc.microarray.description.SADLDescription.Name;

/**
 * Tool edito tool model
 * @author Gintare Pacauskaite
 *
 */
public class Tool extends BasicModel{
	
	private static final long serialVersionUID = -6173788013713655305L;
	private Label lbModule;
	private Label lbCategory;
	
	private ComboBox module;
	private ComboBox category;
	
	public Tool(ToolEditor root) {
		this.root = root;
		createUI();
	}
	
	@Override
	public Tool createUI() {
		generateHeader();
		initElements();
		addRow(lbModule, module);
		addRow(lbCategory, category);
		addRow(lbDescription, description);
		return this;
	}
	
	@Override
	protected void generateHeader() {
		lbTitle.setValue(getBoldText("Tool"));
	}
	
	public Tool createUIwithData(SADLDescription sadlDescription) {
		fillWithData(sadlDescription);
		return this;
	}
	
	private void initElements() {
		lbId.setValue("Id:");
		lbModule = new Label("Module:");
		lbCategory = new Label("Category:");
		
		module = new ComboBox();
		module.setWidth(WIDTH);
		
		category = new ComboBox();
		category.setWidth(WIDTH);
		
		id.setImmediate(true);
		name.setRequired(true);
		name.setRequiredError(REQUIRED_TEXT);
		description.setRequired(true);
		description.setRequiredError(REQUIRED_TEXT);
	}
	
	
	private void fillWithData(SADLDescription sadlDescription) {
		id.setValue(sadlDescription.getName().getID());
		name.setValue(sadlDescription.getName().getDisplayName());
		description.setValue(getValue(sadlDescription.getComment()));
	}
	
	/**
	 * Creates SADL tool
	 * @return SADL tool, or null if mandatory fields was not filled up
	 */
	public SADLDescription createSadlDescription() {
		if(id.isValid() && name.isValid() && description.isValid()) {
			Name nname = Name.createEmptyName();
			nname.setID(id.getValue());
			if(!name.getValue().isEmpty())
				nname.setDisplayName(name.getValue());
			SADLDescription sadlDescription = new SADLDescription(nname);
			if(getValueOrNull(description.getValue()) != null)
			sadlDescription.setComment(description.getValue());
			return sadlDescription;
		} else {
			return null;
		}
	}

	@Override
	protected String getType() {
		// TODO Auto-generated method stub
		return null;
	}
	
	/**
	 * Generates tool title
	 * @return new tool title
	 */
	public String getTitle() {
		return getTitle(module.getValue(), category.getValue(), name.getValue(), id.getValue());
	}
	
	/**
	 * Generates tool title with new id
	 * @param id
	 * @return new tool title
	 */
	public String getTitleId(String id) {
		return getTitle(module.getValue(), category.getValue(), name.getValue(), id);
	}
	
	/**
	 * Generates new tool title with new display name
	 * @param displayName
	 * @return new tool title
	 */
	public String getTitleDisplayName(String displayName) {
		return getTitle(module.getValue(), category.getValue(), displayName, id.getValue());
	}
	
	/**
	 * Tool title template
	 * @param module
	 * @param category
	 * @param displayName
	 * @param id
	 * @return generated by tamplete tool title
	 */
	public String getTitle(Object module, Object category, String displayName, String id) {
		StringBuilder title = new StringBuilder();
		if(module != null) {
			title.append(module);
			title.append(" /");
		}
		if(category != null) {
			title.append(" " + category);
			title.append(" /");
		}
		if(displayName != null && !displayName.isEmpty())
			title.append(" " + displayName);
		if(id != null && !id.isEmpty()) {
			title.append(" (" + id + ")");
		}
		return title.toString();
	}
	
	public void setToTitle(String title) {
		lbTitleDescription.setValue(getBoldText(title));
	}
}
