#!/bin/bash

ACTIVEMQ_START_DELAY=10

CHIPSTER_HOME="$(dirname "$(readlink -f ${BASH_SOURCE[0]})")"
# platform, should be linux-x86-32 or linux-x86-64, autodetected if not set
PLATFORM=""


## detect if platform not set
if [ ! $PLATFORM ]; then
    ARCH=`uname -m`
    if [ "$ARCH" = "i686" ]; then
	PLATFORM="linux-x86-32"
    elif [ "$ARCH" = "x86_64" ]; then
	PLATFORM="linux-x86-64"
    else
	echo "Could not detect hardware architecture, please set platform manually."
	exit -1;
    fi
fi

run() {
    # run command if directory exists
    if [ -d $CHIPSTER_HOME/$1 ]; then
    	
    	# pick binary file name
    	if [ "$1" == "activemq" ]; then
        	BIN_FILE=$1
		else 
        	BIN_FILE=chipster-$1
		fi
		
		# run the command
        $CHIPSTER_HOME/$1/bin/$PLATFORM/$BIN_FILE $2
    
    	# wait if needed    
        if [ "$1" == "activemq" ]; then
	        if [ "$2" == "start" ]; then
    			echo Waiting $ACTIVEMQ_START_DELAY seconds for ActiveMQ to start...
    			sleep $ACTIVEMQ_START_DELAY
    		fi
    	fi
    	
    fi
}


start() {
	run activemq start
    run fileserver start
    run webstart start
    run auth start
    run comp start
    run manager start
}

stopit() {
    run auth stop
    run comp stop
	run manager stop
    run fileserver stop
    run webstart stop
    run activemq stop
}

status() {
    run activemq status
    run fileserver status
    run webstart status
    run auth status
    run comp status
    run manager status
}

case "$1" in

    'start')
        start
        ;;
    'stop')
        stopit
        ;;
    'restart')
        stopit
        start
        ;;
    'status')
        status
        ;;
    *)
        echo "Usage: chipster { start | stop | restart | status }"
        exit 1
        ;;
esac


exit 0
